LANGUAGES = {
    'ua': {
        'menu_message': '🎮 Головне меню',
        'registration_button': '📝 Реєстрація',
        'forecast_button': '🎯 Прогноз',
        'profile_button': '👤 Профіль',
        'instruction_button': '📖 Інструкція',
        'total_games': 'Всього ігор: {total}',
        'total_wins': 'Всього перемог: {total}',
        'total_deposits': 'Всього депозитів: {total}',
        'referral_stats': 'Статистика рефералів: {data}',
        'deposit_stats': 'Статистика депозитів: {data}',
        'welcome': '👋 Привіт, {username}!',
        'choose_language': 'Оберіть мову:',
        'language_set': '✅ Мову встановлено: Українська',
        'select_language': '🌍 Обрати мову',
        'language_name': '🇺🇦 Українська',
        'main_menu': '📱 Головне меню',
        'registration': '📝 Реєстрація',
        'forecast': '🎮 Прогноз',
        'profile': '👤 Профіль',
        'instruction': '📖 Інструкція',
        'language_selected': 'Ви обрали українську мову',
        'choose_action': 'Оберіть дію:',
        'register': '📝 Реєстрація',
        'forecast': '🔮 Прогноз',
        'profile': '👤 Профіль',
        'instructions': '📚 Інструкція',
        'registration_link': '📝 Для реєстрації перейдіть за посиланням нижче.{link}\nНе забудьте ввести промокод {promo_code} для отримання бонусу!',
        'promo_code': 'Промокод',
    },
    'ru': {
        'menu_message': '🎮 Главное меню',
        'registration_button': '📝 Регистрация',
        'forecast_button': '🎯 Прогноз',
        'profile_button': '👤 Профиль',
        'instruction_button': '📖 Инструкция',
        'total_games': 'Всего игр: {total}',
        'total_wins': 'Всего побед: {total}',
        'total_deposits': 'Всего депозитов: {total}',
        'referral_stats': 'Статистика рефералов: {data}',
        'deposit_stats': 'Статистика депозитов: {data}',
        'welcome': '👋 Привет, {username}!',
        'choose_language': 'Выберите язык:',
        'language_set': '✅ Язык установлен: Русский',
        'select_language': '🌍 Выбрать язык',
        'language_name': '🇷🇺 Русский',
        'main_menu': '📱 Главное меню',
        'registration': '📝 Регистрация',
        'forecast': '🎮 Прогноз',
        'profile': '👤 Профиль',
        'instruction': '📖 Инструкция',
        'language_selected': 'Вы выбрали русский язык',
        'choose_action': 'Выберите действие:',
        'register': '📝 Регистрация',
        'forecast': '🔮 Прогноз',
        'profile': '👤 Профиль',
        'instructions': '📚 Инструкция',
        'registration_link': '📝 Для регистрации перейдите по ссылке ниже.{link}\nНе забудьте ввести промокод {promo_code} для получения бонуса!',
        'promo_code': 'Промокод',
    },
    'en': {
        'menu_message': '🎮 Main Menu',
        'registration_button': '📝 Registration',
        'forecast_button': '🎯 Forecast',
        'profile_button': '👤 Profile',
        'instruction_button': '📖 Instructions',
        'total_games': 'Total games: {total}',
        'total_wins': 'Total wins: {total}',
        'total_deposits': 'Total deposits: {total}',
        'referral_stats': 'Referral statistics: {data}',
        'deposit_stats': 'Deposit statistics: {data}',
        'welcome': '👋 Hello, {username}!',
        'choose_language': 'Choose language:',
        'language_set': '✅ Language set: English',
        'select_language': '🌍 Select language',
        'language_name': '🇺🇸 English',
        'main_menu': '📱 Main Menu',
        'registration': '📝 Registration',
        'forecast': '🎮 Forecast',
        'profile': '👤 Profile',
        'instruction': '📖 Instruction',
        'language_selected': 'You have selected English',
        'choose_action': 'Choose an action:',
        'register': '📝 Register',
        'forecast': '🔮 Forecast',
        'profile': '👤 Profile',
        'instructions': '📚 Instructions',
        'registration_link': '📝 To register, follow the link below.{link}\nDon\'t forget to enter the promo code {promo_code} to get your bonus!',
        'promo_code': 'Promo code',
    }
}
